export enum ErrorCode {
  TOKEN_IS_EXPIRED = "TOKEN_IS_EXPIRED",
  UNAUTHORIZED = "UNAUTHORIZED",
  FORBIDDEN = "FORBIDDEN",
  USERNAME_NOT_FOUND = "USERNAME_NOT_FOUND",
  NOT_FOUND = "NOT_FOUND",
  BAD_REQUEST = "BAD_REQUEST",
  PASSWORD_IS_INCORRECT = "PASSWORD_IS_INCORRECT",
  MENU_NOT_FOUND = "MENU_NOT_FOUND",
  PARENT_MENU_NOT_FOUND = "PARENT_MENU_NOT_FOUND",
}
